### ISSUE TITLE
Bug: commas are treated as optional everywhere, but shouldn't be.

### ISSUE THREAD

**Issue by matey-jack** [etienne-dldc/literal-parser#13]
According to JavaScript spec `Parser.parse('{ one: 1 two: 2 });` should throw because of invalid syntax.

or are you trying to make it more lenient by design?

in my use-case, getting an error here would be super essential because I am validating that some data good to be read by a Browser later. Basically, I need the tool to tell me to add the missing comma.

**Comment by etienne-dldc** [comment]
Hi,

thanks for reporting the issue. It should be fixed by https://github.com/etienne-dldc/literal-parser/releases/tag/v3.0.2

**Comment by matey-jack** [comment]
thanks so much! I just upgraded, re-ran my test, and it's green 😍
