### ISSUE TITLE
Feature Request: Configurable Spacing Options in Serializer

### ISSUE THREAD

**Issue by alvarolb** [etienne-dldc/literal-parser#18]
Hello,

Firstly, I'd like to express my gratitude for developing this well-crafted library; it has been functioning quite well.

I wanted to propose an enhancement regarding the serializer's formatting options. Would it be possible to introduce a feature that allows users to configure the spacing, similar to the functionality available in JSON.stringify()? Currently, the output is generated in a single line, which can sometimes make it difficult to read.

Thank you for considering this suggestion.

Best regards.

**Comment by etienne-dldc** [comment]
Hi,

Glad you like it 😃 

I agree it's a nice feature to have so I've just implemented it.

It's available in the new `3.1.0` version and I've updated the README with the different options available 😉
Feel free to tell what you think !

✌️

**Comment by alvarolb** [comment]
Hello,

Thank you for the swift implementation of the feature! 🙏 

I just tried it out with the 3.1.0 version, and it works seamlessly. The additional options in the README are very helpful and make it even more versatile. I appreciate your receptiveness to community suggestions and your continuous efforts to enhance the library! 

Keep up the great work, and thanks once again! 👍
